
eureka :
  instance :
    hostname : localhost
    preferIpAddress : true
  client :
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone : http://${eureka.instance.hostname}:8762/eureka/
