server :
  port : 8762
eureka :
  instance :
    hostname : eureka-server
  client :
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
